using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using QuanLyNhanSu.Models;
using System.Data.SqlClient;

namespace QuanLyNhanSu.Views
{
    public partial class uctXoaNV : DevExpress.XtraEditors.XtraUserControl
    {
        AccessDataBase db = new AccessDataBase();
        DataTable dttb = new DataTable();
        public uctXoaNV()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
        }
        public static uctXoaNV xoanv = new uctXoaNV();

        private void uctXoaNV_Load(object sender, EventArgs e)
        {
            string query = "Select * From NhanVien";
            db.readDatathroughAdapter(query, dttb);
            dgvXoaNV.DataSource = dttb;
        }

        private void bt1_Click(object sender, EventArgs e)
        {
            if(dgvXoaNV.RowCount == 0)
            {
                bt1.Enabled = false;
            }
            else if(MessageBox.Show("Bạn có chắc chắn xóa dòng này không?", "DELETE", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                // Chỉ mục hiện tại
                int selectIndex = dgvXoaNV.SelectedRows[0].Index;
                string MaNV = Convert.ToString(dgvXoaNV[0, selectIndex].Value);
                //query
                string sql = "DELETE FROM NhanVien Where MaNV = '" + MaNV + "' ;";
                SqlCommand deteRow = new SqlCommand(sql);
                db.executeQuery(deteRow);
                //Remove khỏi datagird
                dgvXoaNV.Rows.RemoveAt(selectIndex);
            }
           
        }
    }
}
