using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using QuanLyNhanSu.Models;
using System.Data.SqlClient;

namespace QuanLyNhanSu.Views
{
    public partial class uctXoaNV : DevExpress.XtraEditors.XtraUserControl
    {
        AccessDataBase db = new AccessDataBase();
        public uctXoaNV()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously
        }
        public static uctXoaNV xoanv = new uctXoaNV();

        private void uctXoaNV_Load(object sender, EventArgs e)
        {
            DataTable dttbLoad = new DataTable();
            string query = "Select * From NhanVien";
            db.readDatathroughAdapter(query, dttbLoad);
            dgvXoaNV.DataSource = dttbLoad;
        }
        private void RefeshList()
        {
            DataTable dttbLoad = new DataTable();
            string query = "Select * From NhanVien";
            db.readDatathroughAdapter(query, dttbLoad);
            dgvXoaNV.DataSource = dttbLoad;
        }
        private void bt1_Click(object sender, EventArgs e)
        {
            if(dgvXoaNV.RowCount == 0)
            {
                bt1.Enabled = false;
            }
            else if(XtraMessageBox.Show("Bạn có chắc chắn xóa dòng này không?", "Cảnh Báo", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                // Chỉ mục hiện tại
                int selectIndex = dgvXoaNV.SelectedRows[0].Index;
                string MaNV = Convert.ToString(dgvXoaNV[0, selectIndex].Value);
                //query
                string sql = "DELETE FROM NhanVien Where MaNV = '" + MaNV + "' ;";
                SqlCommand deteRow = new SqlCommand(sql);
                db.executeQuery(deteRow);
                //Remove khỏi datagird
                dgvXoaNV.Rows.RemoveAt(selectIndex);
                //dgvXoaNV.DataSource = dttbLoad;
                this.RefeshList();
            }

        }

        private void btTimKiem_Click(object sender, EventArgs e)
        {
            string sql = "SELECT  nv.* FROM NhanVien nv " +
                "JOIN PhongBan pb On nv.MaPhongBan = pb.MaPhongBan " +
                "JOIN ChucVu cv ON nv.MaCV = cv.MaCV " +
                "WHERE nv.MaNV LIKE N'%" + tbMaNV.Text + "' " +
                "AND nv.HoTen LIKE N'%" + tbHoTen.Text + "' " +
                "And pb.TenPhongBan LIKE N'%" + cbPhongBan.Text + "' " +
                "AND cv.TenCV Like N'%" + cbChucVu.Text + "' ";
            DataTable dttb = new DataTable();
            db.readDatathroughAdapter(sql, dttb);
            dgvXoaNV.DataSource = dttb;
        }
    }
}
